import test from 'node:test';
import assert from 'node:assert/strict';
import {createHumanModel,updateHumanModel,applyHumanModelEvidenceReview,humanModelFactCandidates,applyHumanModelFactPromotion,reconcileHumanModelFactPromotions,humanModelFactPromotionAudit} from '../src/core/human-model.js';
function repeated(){let model=createHumanModel({profile:{name:'Pedro'}});for(const at of ['2026-07-01T10:00:00Z','2026-07-08T10:00:00Z','2026-07-15T10:00:00Z']){model=updateHumanModel(model,{context:{sleep:3,energy:2,time:15,challenge:'body',soreness:'none',emotionalLoad:'usual'},at});const obs=model.observations.find(item=>item.key==='body.energySignal'&&item.observedAt===at);model=applyHumanModelEvidenceReview(model,{evidenceId:obs.id,action:'confirm',at})}return model}
test('three matching confirmed observations create a candidate',()=>{const c=humanModelFactCandidates(repeated(),{now:Date.parse('2026-07-21T10:00:00Z')}).find(i=>i.key==='body.energySignal');assert.ok(c);assert.equal(c.evidenceCount,3)});
test('reported observations alone cannot create a candidate',()=>{let m=createHumanModel({});for(const at of ['2026-07-01T10:00:00Z','2026-07-08T10:00:00Z','2026-07-15T10:00:00Z'])m=updateHumanModel(m,{context:{sleep:3,energy:2,time:15,challenge:'body',soreness:'none',emotionalLoad:'usual'},at});assert.equal(humanModelFactCandidates(m,{now:Date.parse('2026-07-21T10:00:00Z')}).length,0)});
test('person promotion creates a stable confirmed fact',()=>{const m=repeated(),c=humanModelFactCandidates(m,{now:Date.parse('2026-07-21T10:00:00Z')}).find(i=>i.key==='body.energySignal'),p=applyHumanModelFactPromotion(m,{candidate:c,action:'promote'}),f=p.facts.find(i=>i.promotionId===c.id);assert.ok(f);assert.equal(f.source,'person-promoted')});
test('reject keeps evidence as observations only',()=>{const m=repeated(),c=humanModelFactCandidates(m,{now:Date.parse('2026-07-21T10:00:00Z')})[0],r=applyHumanModelFactPromotion(m,{candidate:c,action:'reject'});assert.ok(!r.facts.some(i=>i.promotionId===c.id))});
test('reopen removes promoted fact',()=>{let m=repeated();const c=humanModelFactCandidates(m,{now:Date.parse('2026-07-21T10:00:00Z')})[0];m=applyHumanModelFactPromotion(m,{candidate:c,action:'promote'});m=applyHumanModelFactPromotion(m,{candidate:{...c,status:'promoted'},action:'reopen'});assert.ok(!m.facts.some(i=>i.promotionId===c.id))});
test('promotion remains non-influential',()=>{const a=humanModelFactPromotionAudit(repeated(),{now:Date.parse('2026-07-21T10:00:00Z')});assert.equal(a.judgementInfluence,0);assert.equal(a.practiceSelectionInfluence,0);assert.equal(a.safetyInfluence,0)});
test('reconciliation removes orphaned promotions',()=>{const m=repeated();m.promotions=[{candidateId:'missing',status:'promoted'}];assert.equal(reconcileHumanModelFactPromotions(m,{now:Date.parse('2026-07-21T10:00:00Z')}).promotions.length,0)});
