import test from 'node:test';import assert from 'node:assert/strict';import{assessPatternTransfer,decayOutcomePattern,registerCounterEvidence,createTransferRecord,rejectTransferRecord,reconcilePatternTransfers,contextKeySimilarity}from'../src/core/pattern-transfer.js';import{migrateV0140Phase1ToPhase2}from'../src/core/state-schema.js';
const pattern={id:'p1',practiceId:'walk',contextKey:'body|mild|usual',status:'stable',observations:5,eligibleObservations:5,positive:5,neutral:0,negative:0,causalStrength:.8,lastObservedAt:'2026-07-20T10:00:00.000Z'};
test('highly similar stable pattern transfers cautiously',()=>{const r=assessPatternTransfer(pattern,{targetContextKey:'body|mild|usual',targetPracticeId:'walk',now:new Date('2026-07-21').getTime()});assert.equal(r.status,'supported');assert.equal(r.applies,true);assert.ok(r.weight<=.14)});
test('different practice blocks transfer',()=>{const r=assessPatternTransfer(pattern,{targetContextKey:'body|mild|usual',targetPracticeId:'strength'});assert.equal(r.status,'blocked');assert.equal(r.applies,false)});
test('materially different context blocks transfer',()=>{assert.equal(assessPatternTransfer(pattern,{targetContextKey:'family|significant|heavy',targetPracticeId:'walk'}).status,'blocked')});
test('old stable pattern decays back to emerging',()=>{const r=decayOutcomePattern(pattern,new Date('2027-08-01').getTime());assert.equal(r.status,'emerging');assert.equal(r.decayFactor,.45)});
test('counter-evidence can destabilise a pattern',()=>{let r={...pattern};r=registerCounterEvidence(r,{effect:'worse',causalStrength:.2});r=registerCounterEvidence(r,{effect:'worse',causalStrength:.2});r=registerCounterEvidence(r,{effect:'worse',causalStrength:.2});r=registerCounterEvidence(r,{effect:'worse',causalStrength:.2});assert.equal(r.status,'emerging');assert.ok(r.contradictions>=2)});
test('transfer record can be rejected',()=>{const assessment=assessPatternTransfer(pattern,{targetContextKey:'body|mild|usual',targetPracticeId:'walk'}),record=createTransferRecord({pattern,targetContextKey:'body|mild|usual',assessment}),rejected=rejectTransferRecord([record],{transferId:record.id,note:'Exceptional context.'});assert.equal(rejected[0].status,'rejected');assert.equal(rejected[0].rejectionNote,'Exceptional context.')});
test('reconciliation removes orphans and duplicates',()=>{const assessment=assessPatternTransfer(pattern,{targetContextKey:'body|mild|usual',targetPracticeId:'walk'}),record=createTransferRecord({pattern,targetContextKey:'body|mild|usual',assessment}),state=reconcilePatternTransfers({outcomePatterns:[pattern],patternTransfers:[record,{...record},{...record,id:'orphan',patternId:'missing'}]},new Date('2026-07-21').getTime());assert.equal(state.patternTransfers.length,1);assert.equal(contextKeySimilarity('a|b|c','a|b|x'),.667)});
test('phase 1 state migrates to schema 23 transfer model',()=>{const m=migrateV0140Phase1ToPhase2({schemaVersion:22});assert.equal(m.schemaVersion,23);assert.equal(m.productVersion,'0.14.0');assert.deepEqual(m.patternTransfers,[])})
